Repository ansible-collections/dellemc.enterprise_sonic, pull requests merged in 2024-11, with the labels that each got.

#473 Fix command deletion for QoS interfaces module
  changelogs/fragments/473-qos-interfaces-deletion-bugfix.yaml
  plugins/module_utils/network/sonic/config/qos_interfaces/qos_interfaces.py
Labels: bug

#464 Ansible support for REST server cipher suite configuration
  changelogs/fragments/464-REST-server-cipher-suite.yaml
  plugins/module_utils/network/sonic/argspec/mgmt_servers/mgmt_servers.py
  plugins/module_utils/network/sonic/config/mgmt_servers/mgmt_servers.py
  plugins/module_utils/network/sonic/facts/mgmt_servers/mgmt_servers.py
  plugins/modules/sonic_mgmt_servers.py
  tests/regression/roles/sonic_mgmt_servers/defaults/main.yml
  tests/unit/modules/network/sonic/fixtures/sonic_mgmt_servers.yaml
Labels: enhancement

#477 Fix functionality to allow a value of 0 to be configured for the appropriate integer attributes and refactor STP module code
  changelogs/fragments/477-stp-bugfix-and-refactor.yaml
  plugins/module_utils/network/sonic/argspec/stp/stp.py
  plugins/module_utils/network/sonic/config/stp/stp.py
  plugins/module_utils/network/sonic/facts/stp/stp.py
  plugins/modules/sonic_stp.py
  tests/unit/modules/network/sonic/fixtures/sonic_stp.yaml
  tests/unit/modules/network/sonic/test_sonic_stp.py
Labels: bug

#478 Adding the "severity" option to the logging module.
  changelogs/fragments/478-Adding-severity-option-to-logging-module.yaml
  plugins/module_utils/network/sonic/argspec/logging/logging.py
  plugins/module_utils/network/sonic/config/logging/logging.py
  plugins/module_utils/network/sonic/facts/logging/logging.py
  plugins/modules/sonic_logging.py
  tests/regression/roles/sonic_logging/defaults/main.yml
  tests/unit/modules/network/sonic/fixtures/sonic_logging.yaml
Labels: enhancement

#462 SSH resource module implementation
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/argspec/ssh/ssh.py
  plugins/module_utils/network/sonic/config/ssh/ssh.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/module_utils/network/sonic/facts/ssh/ssh.py
  plugins/modules/sonic_facts.py
  plugins/modules/sonic_ssh.py
  tests/regression/roles/sonic_ssh/defaults/main.yml
  tests/regression/roles/sonic_ssh/meta/main.yml
  tests/regression/roles/sonic_ssh/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_ssh/tasks/main.yml
  tests/regression/roles/sonic_ssh/tasks/preparation_tests.yaml
  tests/regression/roles/sonic_ssh/tasks/tasks_template.yaml
  tests/regression/test.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_ssh.yaml
  tests/unit/modules/network/sonic/test_sonic_ssh.py
Labels: new_resource_module

#481 Update CoPP reserved names list
  changelogs/fragments/481-copp-bugfix.yaml
  plugins/module_utils/network/sonic/config/copp/copp.py
Labels: bug

#484 Provide a release note and other updates for the 3.0.0 release.
  CHANGELOG.rst
  README.md
  changelogs/.plugin-cache.yaml
  changelogs/archive_fragments/3.0.0/296-new-vlan-mapping-resource-module.yaml
  changelogs/archive_fragments/3.0.0/380-sonic-image-verification.yaml
  changelogs/archive_fragments/3.0.0/382-aaa-breaking-change.yaml
  changelogs/archive_fragments/3.0.0/414-ldap-security-profile.yaml
  changelogs/archive_fragments/3.0.0/421-set-new-native-option-ipv-ipv6-next-hop.yaml
  changelogs/archive_fragments/3.0.0/423-syslog-over-TLS.yaml
  changelogs/archive_fragments/3.0.0/424-remote-audit-log.yaml
  changelogs/archive_fragments/3.0.0/434-changelogs-post-release-2.5.0-pylint-and-doc-fixes.yaml
  changelogs/archive_fragments/3.0.0/440-bgp-aann-support-merged-fix.yaml
  changelogs/archive_fragments/3.0.0/441-system-downward-compatibility-fix.yaml
  changelogs/archive_fragments/3.0.0/443-update-regex-edit-config.yaml
  changelogs/archive_fragments/3.0.0/444-add-buffer-init-attribute.yaml
  changelogs/archive_fragments/3.0.0/445-ConnectionError-add-imports.yaml
  changelogs/archive_fragments/3.0.0/446-README-documentation-links-fix.yaml
  changelogs/archive_fragments/3.0.0/448-set-suppress-vlan-neigh-option.yaml
  changelogs/archive_fragments/3.0.0/453-add-unreliable-los-option-to-interface.yaml
  changelogs/archive_fragments/3.0.0/455-fix-vrrp-regression-failure.yaml
  changelogs/archive_fragments/3.0.0/456-tests-sanity-ignore-action-plugin-for-ansible-2.19.yaml
  changelogs/archive_fragments/3.0.0/459-add-new-message-type.yaml
  changelogs/archive_fragments/3.0.0/460-stp-long-int-vlan-fix.yaml
  changelogs/archive_fragments/3.0.0/463-mclag-prereq-member-deletion.yaml
  changelogs/archive_fragments/3.0.0/464-REST-server-cipher-suite.yaml
  changelogs/archive_fragments/3.0.0/465-update-qos-wred-test-case.yaml
  changelogs/archive_fragments/3.0.0/466-ospf-area-bugfix.yaml
  changelogs/archive_fragments/3.0.0/470-interfaces-speed-bugfix.yaml
  changelogs/archive_fragments/3.0.0/471-fix-vxlan-regression-tests.yaml
  changelogs/archive_fragments/3.0.0/473-qos-interfaces-deletion-bugfix.yaml
  changelogs/archive_fragments/3.0.0/474-l3_interfaces-ipv6-autoconf-downward-compatibility.yaml
  changelogs/archive_fragments/3.0.0/477-stp-bugfix-and-refactor.yaml
  changelogs/archive_fragments/3.0.0/478-Adding-severity-option-to-logging-module.yaml
  changelogs/archive_fragments/3.0.0/481-copp-bugfix.yaml
  changelogs/archive_fragments/3.0.0/482-radius_server-regression-test-hostname.yaml
  changelogs/archive_fragments/3.0.0/v_3.0.0_summary.yaml
  changelogs/changelog.yaml
  galaxy.yml
Labels: documentation
