Repository ansible-collections/dellemc.enterprise_sonic, pull requests merged in 2024-08, with the labels that each got.

#412 Add mgmt servers module
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/argspec/mgmt_servers/mgmt_servers.py
  plugins/module_utils/network/sonic/config/mgmt_servers/mgmt_servers.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/module_utils/network/sonic/facts/mgmt_servers/mgmt_servers.py
  plugins/modules/sonic_facts.py
  plugins/modules/sonic_mgmt_servers.py
  tests/regression/roles/sonic_mgmt_servers/defaults/main.yml
  tests/regression/roles/sonic_mgmt_servers/meta/main.yaml
  tests/regression/roles/sonic_mgmt_servers/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_mgmt_servers/tasks/main.yml
  tests/regression/roles/sonic_mgmt_servers/tasks/preparation_tests.yaml
  tests/regression/roles/sonic_mgmt_servers/tasks/tasks_template.yaml
  tests/regression/test.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_mgmt_servers.yaml
  tests/unit/modules/network/sonic/test_sonic_mgmt_servers.py
Labels: new_resource_module

#385 OSPFv2_interfaces - Add Enterprise SONiC resource module
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/argspec/ospfv2_interfaces/__init__.py
  plugins/module_utils/network/sonic/argspec/ospfv2_interfaces/ospfv2_interfaces.py
  plugins/module_utils/network/sonic/config/ospfv2_interfaces/__init__.py
  plugins/module_utils/network/sonic/config/ospfv2_interfaces/ospfv2_interfaces.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/module_utils/network/sonic/facts/ospfv2_interfaces/__init__.py
  plugins/module_utils/network/sonic/facts/ospfv2_interfaces/ospfv2_interfaces.py
  plugins/modules/sonic_facts.py
  plugins/modules/sonic_ospfv2_interfaces.py
  tests/regression/roles/sonic_ospfv2_interfaces/defaults/main.yml
  tests/regression/roles/sonic_ospfv2_interfaces/meta/main.yml
  tests/regression/roles/sonic_ospfv2_interfaces/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_ospfv2_interfaces/tasks/main.yml
  tests/regression/roles/sonic_ospfv2_interfaces/tasks/preparation_tests.yaml
  tests/regression/roles/sonic_ospfv2_interfaces/tasks/tasks_template.yaml
  tests/regression/test.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_ospfv2_interfaces.yaml
  tests/unit/modules/network/sonic/test_sonic_ospfv2_interfaces.py
Labels: new_resource_module

#402 Ospfv2 area
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/argspec/ospf_area/ospf_area.py
  plugins/module_utils/network/sonic/config/ospf_area/ospf_area.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/module_utils/network/sonic/facts/ospf_area/ospf_area.py
  plugins/module_utils/network/sonic/utils/utils.py
  plugins/modules/sonic_facts.py
  plugins/modules/sonic_ospf_area.py
  tests/regression/roles/sonic_ospf_area/defaults/main.yml
  tests/regression/roles/sonic_ospf_area/meta/main.yaml
  tests/regression/roles/sonic_ospf_area/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_ospf_area/tasks/main.yml
  tests/regression/roles/sonic_ospf_area/tasks/preparation_tests.yaml
  tests/regression/roles/sonic_ospf_area/tasks/tasks_template.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_ospf_area.yaml
  tests/unit/modules/network/sonic/test_sonic_ospf_area.py
Labels: new_resource_module

#432 Release 2.5.0: Release notes
  .github/workflows/ansible-test.yml
  CHANGELOG.rst
  README.md
  changelogs/.plugin-cache.yaml
  changelogs/archive_fragments/2.5.0/299-mclag-session-vrf-support.yaml
  changelogs/archive_fragments/2.5.0/317-added-protocol-option-for-syslog-module.yaml
  changelogs/archive_fragments/2.5.0/328-playbook-check-diff-modes-for-l3-interfaces.yaml
  changelogs/archive_fragments/2.5.0/329-regression-test-automated-intf-naming-config.yaml
  changelogs/archive_fragments/2.5.0/330-add-external-ip-attribute-for-vxlan.yaml
  changelogs/archive_fragments/2.5.0/331-playbook-check-diff-modes-for-route_maps_prefix_lists.yaml
  changelogs/archive_fragments/2.5.0/335-replaced-overridden-for-bgp-neighbors-module.yaml
  changelogs/archive_fragments/2.5.0/336-replaced-overridden-for-bgp-neighbors-af-module.yaml
  changelogs/archive_fragments/2.5.0/337-playbook-check-diff-modes-for-mclag-port-breakout-vxlans.yaml
  changelogs/archive_fragments/2.5.0/338-playbook-check-diff-modes-for-mac-stp-lldp.yaml
  changelogs/archive_fragments/2.5.0/342-system-auto-breakout-module.yaml
  changelogs/archive_fragments/2.5.0/344-update-ut-config-requests-validation.yaml
  changelogs/archive_fragments/2.5.0/346-playbook-check-diff-modes-for-bfd-copp-dhcps.yaml
  changelogs/archive_fragments/2.5.0/350-playbook-check-diff-modes-for-bgp-modules.yaml
  changelogs/archive_fragments/2.5.0/351-bgp-af-import-vrf-support.yaml
  changelogs/archive_fragments/2.5.0/352-system-standard-extended-interface-naming.yaml
  changelogs/archive_fragments/2.5.0/354-prefix-lists-fix-replaced-idempotency.yaml
  changelogs/archive_fragments/2.5.0/360-playbook-check-diff-modes-for-bgp-neighbors-and-af.yaml
  changelogs/archive_fragments/2.5.0/364-interfaces-fix-loopback.yaml
  changelogs/archive_fragments/2.5.0/366-github-issue-357-fix.yaml
  changelogs/archive_fragments/2.5.0/373-qos-scheduler-update-states.yaml
  changelogs/archive_fragments/2.5.0/374-usgv6r1-related-features-support.yaml
  changelogs/archive_fragments/2.5.0/377-interfaces-vlans-fix-facts.yaml
  changelogs/archive_fragments/2.5.0/381-fix-copp-states.yaml
  changelogs/archive_fragments/2.5.0/383-fix-state-implementation.yaml
  changelogs/archive_fragments/2.5.0/384-add-route-maps-ut.yaml
  changelogs/archive_fragments/2.5.0/388-system-update-replaced-state.yaml
  changelogs/archive_fragments/2.5.0/391-fix-qos-pfc-bug.yaml
  changelogs/archive_fragments/2.5.0/393-github-issue-376-fix.yaml
  changelogs/archive_fragments/2.5.0/394-update-version-remove-facts-reports.yaml
  changelogs/archive_fragments/2.5.0/395-comment-out-pfc-pg-test-cases.yaml
  changelogs/archive_fragments/2.5.0/396-port-group-facts-enhancement.yaml
  changelogs/archive_fragments/2.5.0/398-bgp-af-aggregate-address-support.yaml
  changelogs/archive_fragments/2.5.0/400-bgp-af-update-replaced-state.yaml
  changelogs/archive_fragments/2.5.0/401-versatile-hash.yaml
  changelogs/archive_fragments/2.5.0/403-lag-interface-evpn-ethernet-segment.yaml
  changelogs/archive_fragments/2.5.0/405-auditd-config.yaml
  changelogs/archive_fragments/2.5.0/410-sonic_l2_interfaces-fix-facts-exception.yaml
  changelogs/archive_fragments/2.5.0/413-route-maps-set-tag-support-and-doc-updates.yaml
  changelogs/archive_fragments/2.5.0/417-bgp-asn-notation.yaml
  changelogs/archive_fragments/2.5.0/418-github-issue-416-fix.yaml
  changelogs/archive_fragments/2.5.0/422-update-ut-for-bgp-neighbors.yaml
  changelogs/archive_fragments/2.5.0/428-l3-interfaces-default-dad-fix.yaml
  changelogs/archive_fragments/2.5.0/429-cliconf-doc-fix.yaml
  changelogs/archive_fragments/2.5.0/431-l3-interfaces-fix-replaced-state.yaml
  changelogs/archive_fragments/2.5.0/432-changelogs-v2.5.0-release-note.yaml
  changelogs/archive_fragments/2.5.0/v2.5.0_summary.yaml
  changelogs/changelog.yaml
  changelogs/config.yaml
  galaxy.yml
  meta/runtime.yml
  tests/regression/hosts
  tests/regression/test.yaml
Labels: documentation

#421 set ip/ipv6 next_hop 'native' option
  changelogs/fragments/421-set-new-native-option-ipv-ipv6-next-hop.yaml
  plugins/module_utils/network/sonic/argspec/route_maps/route_maps.py
  plugins/module_utils/network/sonic/config/route_maps/route_maps.py
  plugins/module_utils/network/sonic/facts/route_maps/route_maps.py
  plugins/modules/sonic_route_maps.py
  tests/regression/roles/sonic_route_maps/defaults/main.yml
  tests/unit/modules/network/sonic/fixtures/sonic_route_maps.yaml
  tests/unit/modules/network/sonic/test_sonic_route_maps.py
Labels: enhancement

#444 Add buffer_init attribute to qos_buffer module
  changelogs/fragments/444-add-buffer-init-attribute.yaml
  playbooks/common_examples/qos_buffer_init.yaml
  plugins/module_utils/network/sonic/argspec/qos_buffer/qos_buffer.py
  plugins/module_utils/network/sonic/config/qos_buffer/qos_buffer.py
  plugins/module_utils/network/sonic/facts/qos_buffer/qos_buffer.py
  plugins/modules/sonic_qos_buffer.py
  tests/regression/roles/sonic_qos_buffer/defaults/main.yml
  tests/regression/roles/sonic_qos_buffer/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_qos_buffer/tasks/main.yml
  tests/regression/roles/sonic_qos_buffer/tasks/preparation_tests.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_qos_buffer.yaml
  tests/unit/modules/network/sonic/test_sonic_qos_buffer.py
Labels: enhancement
