Repository ansible-collections/dellemc.enterprise_sonic, pull requests merged in 2024-10, with the labels that each got.

#448 Set "interface vlanX" 'suppress_vlan_neigh' option
  changelogs/fragments/448-set-suppress-vlan-neigh-option.yaml
  plugins/module_utils/network/sonic/argspec/vxlans/vxlans.py
  plugins/module_utils/network/sonic/config/vxlans/vxlans.py
  plugins/module_utils/network/sonic/facts/vxlans/vxlans.py
  plugins/modules/sonic_vxlans.py
  tests/regression/roles/sonic_vxlan/defaults/main.yml
  tests/unit/modules/network/sonic/fixtures/sonic_vxlans.yaml
  tests/unit/modules/network/sonic/test_sonic_vxlans.py
Labels: enhancement

#465 Update QoS WRED regression test case based on SONiC code changes
  changelogs/fragments/465-update-qos-wred-test-case.yaml
  tests/regression/roles/sonic_qos_wred/defaults/main.yml
Labels: bug

#466 Ospf area bugfix
  changelogs/fragments/466-ospf-area-bugfix.yaml
  plugins/module_utils/network/sonic/config/ospf_area/ospf_area.py
Labels: bug

#469 Fix ansible_password typo
  README.md
Labels: documentation

#470 Remove conditional error message for speed configuration in sonic_interfaces
  changelogs/fragments/470-interfaces-speed-bugfix.yaml
  plugins/module_utils/network/sonic/config/interfaces/interfaces.py
Labels: bug
