Repository ansible-collections/dellemc.enterprise_sonic, pull requests merged in 2024-06, with the labels that each got.

#391 Fix bug for QoS PFC module
  changelogs/fragments/391-fix-qos-pfc-bug.yaml
  plugins/module_utils/network/sonic/config/qos_pfc/qos_pfc.py
Labels: bug

#326 Poe
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/argspec/poe/__init__.py
  plugins/module_utils/network/sonic/argspec/poe/poe.py
  plugins/module_utils/network/sonic/config/poe/__init__.py
  plugins/module_utils/network/sonic/config/poe/poe.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/module_utils/network/sonic/facts/poe/__init__.py
  plugins/module_utils/network/sonic/facts/poe/poe.py
  plugins/module_utils/network/sonic/utils/poe_utils.py
  plugins/modules/sonic_facts.py
  plugins/modules/sonic_poe.py
  tests/regression/roles/sonic_poe/defaults/main.yml
  tests/regression/roles/sonic_poe/meta/main.yaml
  tests/regression/roles/sonic_poe/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_poe/tasks/main.yml
  tests/regression/roles/sonic_poe/tasks/preparation_tests.yaml
  tests/regression/roles/sonic_poe/tasks/tasks_template.yaml
  tests/regression/test.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_poe.yaml
  tests/unit/modules/network/sonic/test_sonic_poe.py
Labels: new_resource_module

#375 Add QoS interfaces module
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/argspec/qos_interfaces/__init__.py
  plugins/module_utils/network/sonic/argspec/qos_interfaces/qos_interfaces.py
  plugins/module_utils/network/sonic/config/qos_interfaces/__init__.py
  plugins/module_utils/network/sonic/config/qos_interfaces/qos_interfaces.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/module_utils/network/sonic/facts/qos_interfaces/__init__.py
  plugins/module_utils/network/sonic/facts/qos_interfaces/qos_interfaces.py
  plugins/modules/sonic_facts.py
  plugins/modules/sonic_qos_interfaces.py
  tests/regression/roles/sonic_qos_interfaces/defaults/main.yml
  tests/regression/roles/sonic_qos_interfaces/meta/main.yaml
  tests/regression/roles/sonic_qos_interfaces/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_qos_interfaces/tasks/main.yml
  tests/regression/roles/sonic_qos_interfaces/tasks/preparation_tests.yaml
  tests/regression/roles/sonic_qos_interfaces/tasks/tasks_template.yaml
  tests/regression/test.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_qos_interfaces.yaml
  tests/unit/modules/network/sonic/test_sonic_qos_interfaces.py
Labels: new_resource_module

#396 Make error message for port group facts gathering more descriptive
  changelogs/fragments/396-port-group-facts-enhancement.yaml
  plugins/module_utils/network/sonic/facts/port_group/port_group.py
Labels: enhancement

#372 Add Dell Enterprise SONiC 'ldap' module
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/argspec/ldap/__init__.py
  plugins/module_utils/network/sonic/argspec/ldap/ldap.py
  plugins/module_utils/network/sonic/config/ldap/__init__.py
  plugins/module_utils/network/sonic/config/ldap/ldap.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/module_utils/network/sonic/facts/ldap/__init__.py
  plugins/module_utils/network/sonic/facts/ldap/ldap.py
  plugins/modules/sonic_facts.py
  plugins/modules/sonic_ldap.py
  tests/regression/roles/sonic_ldap/defaults/main.yml
  tests/regression/roles/sonic_ldap/meta/main.yml
  tests/regression/roles/sonic_ldap/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_ldap/tasks/main.yml
  tests/regression/roles/sonic_ldap/tasks/preparation_tests.yaml
  tests/regression/roles/sonic_ldap/tasks/tasks_template.yaml
  tests/regression/test.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_ldap.yaml
  tests/unit/modules/network/sonic/test_sonic_ldap.py
Labels: new_resource_module

#398 Add aggregate address configuration support to BGP AF module
  changelogs/fragments/398-bgp-af-aggregate-address-support.yaml
  plugins/module_utils/network/sonic/argspec/bgp_af/bgp_af.py
  plugins/module_utils/network/sonic/config/bgp_af/bgp_af.py
  plugins/module_utils/network/sonic/facts/bgp_af/bgp_af.py
  plugins/modules/sonic_bgp_af.py
  tests/regression/roles/sonic_bgp_af/defaults/main.yml
  tests/unit/modules/network/sonic/fixtures/sonic_bgp_af.yaml
Labels: enhancement
