Repository ansible-collections/dellemc.enterprise_sonic, pull requests merged in 2025-02, with the labels that each got.

#501 fix ansible-lint errors in playbooks directory
  changelogs/fragments/501-fix-ansible-lint-failures-3.yaml
  playbooks/bgp_l3_fabric/clos-fabric.yaml
  playbooks/bgp_l3_fabric/group_vars/all.yaml
  playbooks/bgp_l3_fabric/group_vars/leaf.yaml
  playbooks/bgp_l3_fabric/group_vars/spine.yaml
  playbooks/bgp_l3_fabric/inventory.yaml
Labels: documentation

#495 AAA bugfix and code refactor
  changelogs/fragments/495-aaa-bugfix.yaml
  plugins/module_utils/network/sonic/argspec/aaa/aaa.py
  plugins/module_utils/network/sonic/config/aaa/aaa.py
  plugins/module_utils/network/sonic/facts/aaa/aaa.py
  plugins/modules/sonic_aaa.py
  tests/regression/roles/sonic_aaa/defaults/main.yml
  tests/regression/roles/sonic_aaa/tasks/main.yml
  tests/regression/roles/sonic_aaa/tasks/preparation_tests.yaml
  tests/regression/roles/sonic_aaa/tasks/tasks_template.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_aaa.yaml
Labels: bug

#468 Add cable_length attribute to QoS interfaces module
  changelogs/fragments/468-cable-length.yaml
  plugins/module_utils/network/sonic/argspec/qos_interfaces/qos_interfaces.py
  plugins/module_utils/network/sonic/config/qos_interfaces/qos_interfaces.py
  plugins/module_utils/network/sonic/facts/qos_interfaces/qos_interfaces.py
  plugins/modules/sonic_qos_interfaces.py
  tests/regression/roles/sonic_qos_interfaces/defaults/main.yml
  tests/regression/roles/sonic_qos_interfaces/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_qos_interfaces/tasks/preparation_tests.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_qos_interfaces.yaml
Labels: enhancement

#509 Add sleep to allow TACACS server config updates to apply to SONiC PAM modules
  changelogs/fragments/509-tacacs-server-bugfix.yaml
  plugins/module_utils/network/sonic/config/tacacs_server/tacacs_server.py
Labels: bug

#518 Fix STP check mode bug
  changelogs/fragments/518-fix-stp-check-mode.yaml
  plugins/module_utils/network/sonic/config/stp/stp.py
  tests/regression/roles/sonic_stp/defaults/main.yml
  tests/unit/modules/network/sonic/fixtures/sonic_stp.yaml
  tests/unit/modules/network/sonic/test_sonic_stp.py
Labels: bug
