Repository ansible-collections/dellemc.enterprise_sonic, pull requests merged in 2025-06, with the labels that each got.

#542 Ansible module for ssh server global parameters.
  meta/runtime.yml
  plugins/action/ssh_server.py
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/argspec/ssh_server/__init__.py
  plugins/module_utils/network/sonic/argspec/ssh_server/ssh_server.py
  plugins/module_utils/network/sonic/config/ssh_server/__init__.py
  plugins/module_utils/network/sonic/config/ssh_server/ssh_server.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/module_utils/network/sonic/facts/ssh_server/__init__.py
  plugins/module_utils/network/sonic/facts/ssh_server/ssh_server.py
  plugins/modules/sonic_facts.py
  plugins/modules/sonic_ssh_server.py
  tests/regression/roles/sonic_ssh_server/defaults/main.yaml
  tests/regression/roles/sonic_ssh_server/meta/main.yaml
  tests/regression/roles/sonic_ssh_server/tasks/main.yaml
  tests/regression/roles/sonic_ssh_server/tasks/preparation_tests.yaml
  tests/regression/roles/sonic_ssh_server/tasks/tasks_template.yaml
  tests/regression/test.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_ssh_server.yaml
  tests/unit/modules/network/sonic/test_sonic_ssh_server.py
Labels: new_resource_module

#461 Add copp_traps to CoPP module as part of FBS feature
  changelogs/fragments/461-copp-traps.yaml
  plugins/module_utils/network/sonic/argspec/copp/copp.py
  plugins/module_utils/network/sonic/config/copp/copp.py
  plugins/module_utils/network/sonic/facts/copp/copp.py
  plugins/modules/sonic_copp.py
  tests/regression/roles/sonic_copp/defaults/main.yml
  tests/regression/roles/sonic_copp/meta/main.yaml
  tests/regression/roles/sonic_copp/tasks/main.yml
  tests/regression/roles/sonic_copp/tasks/preparation_tests.yaml
  tests/regression/roles/sonic_copp/tasks/tasks_template.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_copp.yaml
  tests/unit/modules/network/sonic/test_sonic_copp.py
Labels: enhancement

#547 Add Dell Enterprise Sonic_ptp_default_ds module
  meta/runtime.yml
  plugins/action/ptp_default_ds.py
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/argspec/ptp_default_ds/__init__.py
  plugins/module_utils/network/sonic/argspec/ptp_default_ds/ptp_default_ds.py
  plugins/module_utils/network/sonic/config/ptp_default_ds/__init__.py
  plugins/module_utils/network/sonic/config/ptp_default_ds/ptp_default_ds.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/module_utils/network/sonic/facts/ptp_default_ds/__init__.py
  plugins/module_utils/network/sonic/facts/ptp_default_ds/ptp_default_ds.py
  plugins/modules/sonic_facts.py
  plugins/modules/sonic_ptp_default_ds.py
  tests/regression/roles/sonic_ptp_default_ds/defaults/main.yml
  tests/regression/roles/sonic_ptp_default_ds/meta/main.yml
  tests/regression/roles/sonic_ptp_default_ds/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_ptp_default_ds/tasks/main.yml
  tests/regression/roles/sonic_ptp_default_ds/tasks/preparation_tests.yaml
  tests/regression/roles/sonic_ptp_default_ds/tasks/tasks_template.yaml
  tests/regression/roles/sonic_ptp_default_ds/tasks/tasks_template_del.yaml
  tests/regression/test.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_ptp_default_ds.yaml
  tests/unit/modules/network/sonic/test_sonic_ptp_default_ds.py
Labels: new_resource_module

#552 Added Ansible support for PTP_PORT_DS for Dell Enterprise edition
  meta/runtime.yml
  plugins/action/ptp_port_ds.py
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/argspec/ptp_port_ds/__init__.py
  plugins/module_utils/network/sonic/argspec/ptp_port_ds/ptp_port_ds.py
  plugins/module_utils/network/sonic/config/ptp_port_ds/__init__.py
  plugins/module_utils/network/sonic/config/ptp_port_ds/ptp_port_ds.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/module_utils/network/sonic/facts/ptp_port_ds/__init__.py
  plugins/module_utils/network/sonic/facts/ptp_port_ds/ptp_port_ds.py
  plugins/module_utils/network/sonic/utils/interfaces_util.py
  plugins/modules/sonic_facts.py
  plugins/modules/sonic_ptp_port_ds.py
  tests/regression/roles/sonic_ptp_port_ds/defaults/main.yml
  tests/regression/roles/sonic_ptp_port_ds/meta/main.yml
  tests/regression/roles/sonic_ptp_port_ds/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_ptp_port_ds/tasks/main.yml
  tests/regression/roles/sonic_ptp_port_ds/tasks/preparation_tests.yaml
  tests/regression/roles/sonic_ptp_port_ds/tasks/tasks_template.yaml
  tests/regression/test.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_ptp_port_ds.yaml
  tests/unit/modules/network/sonic/test_sonic_ptp_port_ds.py
Labels: new_resource_module

#566 Fix BGP regression failure
  changelogs/fragments/566-bgp-regression-test-fix.yaml
  tests/regression/roles/sonic_bgp/defaults/main.yml
  tests/regression/roles/sonic_bgp/meta/main.yaml
  tests/regression/roles/sonic_bgp/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_bgp/tasks/main.yml
  tests/regression/roles/sonic_bgp/tasks/preparation_tests.yaml
  tests/regression/roles/sonic_bgp/tasks/tasks_template.yaml
  tests/regression/roles/sonic_bgp/templates/cli_test_case_01.cfg
Labels: bug

#569 Fix VRFs bug for overridden state
  changelogs/fragments/569-vrfs-bugfix.yaml
  playbooks/common_examples/mgmt_vrf_off.yaml
  plugins/module_utils/network/sonic/config/vrfs/vrfs.py
  plugins/modules/sonic_vrfs.py
Labels: bug

#544 Add Dell Enterprise SONiC 'pms' module
  meta/runtime.yml
  plugins/action/pms.py
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/argspec/pms/__init__.py
  plugins/module_utils/network/sonic/argspec/pms/pms.py
  plugins/module_utils/network/sonic/config/pms/__init__.py
  plugins/module_utils/network/sonic/config/pms/pms.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/module_utils/network/sonic/facts/pms/__init__.py
  plugins/module_utils/network/sonic/facts/pms/pms.py
  plugins/modules/sonic_facts.py
  plugins/modules/sonic_pms.py
  tests/regression/roles/sonic_pms/defaults/main.yml
  tests/regression/roles/sonic_pms/meta/main.yml
  tests/regression/roles/sonic_pms/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_pms/tasks/main.yml
  tests/regression/roles/sonic_pms/tasks/preparation_tests.yaml
  tests/regression/roles/sonic_pms/tasks/tasks_template.yaml
  tests/regression/test.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_pms.yaml
  tests/unit/modules/network/sonic/test_sonic_pms.py
Labels: new_resource_module
