Repository ansible-collections/dellemc.enterprise_sonic, pull requests merged in 2025-01, with the labels that each got.

#498 Fix ansible lint errors in some module files
  changelogs/fragments/498-fix-ansible-lint-failures.yaml
  plugins/modules/sonic_ospfv2.py
  plugins/modules/sonic_ospfv2_interfaces.py
  plugins/modules/sonic_pim_global.py
  plugins/modules/sonic_pim_interfaces.py
  plugins/modules/sonic_pki.py
  plugins/modules/sonic_poe.py
  plugins/modules/sonic_port_breakout.py
  plugins/modules/sonic_port_group.py
  plugins/modules/sonic_prefix_lists.py
  plugins/modules/sonic_qos_buffer.py
  plugins/modules/sonic_qos_interfaces.py
  plugins/modules/sonic_qos_pfc.py
  plugins/modules/sonic_qos_wred.py
  plugins/modules/sonic_radius_server.py
  plugins/modules/sonic_roce.py
  plugins/modules/sonic_route_maps.py
  plugins/modules/sonic_sflow.py
  plugins/modules/sonic_ssh.py
  plugins/modules/sonic_static_routes.py
  plugins/modules/sonic_stp.py
  plugins/modules/sonic_system.py
  plugins/modules/sonic_tacacs_server.py
  plugins/modules/sonic_vlan_mapping.py
  plugins/modules/sonic_vlans.py
  plugins/modules/sonic_vrfs.py
  plugins/modules/sonic_vxlans.py
Labels: documentation

#447 Add LST resource module
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/argspec/lst/__init__.py
  plugins/module_utils/network/sonic/argspec/lst/lst.py
  plugins/module_utils/network/sonic/config/lst/__init__.py
  plugins/module_utils/network/sonic/config/lst/lst.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/module_utils/network/sonic/facts/lst/__init__.py
  plugins/module_utils/network/sonic/facts/lst/lst.py
  plugins/modules/sonic_facts.py
  plugins/modules/sonic_lst.py
  tests/regression/roles/sonic_lst/defaults/main.yml
  tests/regression/roles/sonic_lst/meta/main.yaml
  tests/regression/roles/sonic_lst/tasks/main.yml
  tests/regression/roles/sonic_lst/tasks/tasks_template.yaml
  tests/regression/test.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_lst.yaml
  tests/unit/modules/network/sonic/test_sonic_lst.py
Labels: new_resource_module

#406 Added ansible support for LLDP TLVs(port-vlan-id, vlan-name, link-aggregation, maximum-frame-size)
  changelogs/fragments/406-lldp-tlv-support.yaml
  plugins/module_utils/network/sonic/argspec/lldp_interfaces/lldp_interfaces.py
  plugins/module_utils/network/sonic/config/lldp_interfaces/lldp_interfaces.py
  plugins/module_utils/network/sonic/facts/lldp_interfaces/lldp_interfaces.py
  plugins/modules/sonic_lldp_interfaces.py
  tests/regression/roles/sonic_lldp_interfaces/defaults/main.yml
  tests/unit/modules/network/sonic/fixtures/sonic_lldp_interfaces.yaml
  tests/unit/modules/network/sonic/test_sonic_lldp_interfaces.py
Labels: enhancement

#490 Add FBS classifiers resource module
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/argspec/fbs_classifiers/__init__.py
  plugins/module_utils/network/sonic/argspec/fbs_classifiers/fbs_classifiers.py
  plugins/module_utils/network/sonic/config/fbs_classifiers/__init__.py
  plugins/module_utils/network/sonic/config/fbs_classifiers/fbs_classifiers.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/module_utils/network/sonic/facts/fbs_classifiers/__init__.py
  plugins/module_utils/network/sonic/facts/fbs_classifiers/fbs_classifiers.py
  plugins/modules/sonic_facts.py
  plugins/modules/sonic_fbs_classifiers.py
  tests/regression/roles/sonic_fbs_classifiers/defaults/main.yml
  tests/regression/roles/sonic_fbs_classifiers/meta/main.yaml
  tests/regression/roles/sonic_fbs_classifiers/tasks/cleanup.yaml
  tests/regression/roles/sonic_fbs_classifiers/tasks/main.yml
  tests/regression/roles/sonic_fbs_classifiers/tasks/preparation.yaml
  tests/regression/roles/sonic_fbs_classifiers/tasks/tasks_template.yaml
  tests/regression/test.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_fbs_classifiers.yaml
  tests/unit/modules/network/sonic/test_sonic_fbs_classifiers.py
Labels: new_resource_module
