Repository ansible-collections/dellemc.enterprise_sonic, pull requests merged in 2025-05, with the labels that each got.

#524 LLDP_interfaces - Add support for diff and check mode
  changelogs/fragments/524-lldp-interfaces-check-diff-support.yaml
  plugins/module_utils/network/sonic/config/lldp_interfaces/lldp_interfaces.py
  plugins/module_utils/network/sonic/utils/utils.py
  plugins/modules/sonic_lldp_interfaces.py
  tests/regression/roles/sonic_lldp_interfaces/defaults/main.yml
  tests/regression/roles/sonic_lldp_interfaces/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_lldp_interfaces/tasks/main.yml
  tests/regression/roles/sonic_lldp_interfaces/tasks/preparations_test.yaml
  tests/regression/roles/sonic_lldp_interfaces/tasks/tasks_template.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_lldp_interfaces.yaml
Labels: enhancement

#487 Snc 39010 interface enhancement port group speed error handling
  changelogs/fragments/487-port-group_interface_speed_error-handling_enhancement.yaml
  plugins/module_utils/network/sonic/config/interfaces/interfaces.py
  plugins/module_utils/network/sonic/utils/interfaces_util.py
Labels: enhancement

#507 Add DCBx resource module
  plugins/module_utils/network/sonic/argspec/dcbx/__init__.py
  plugins/module_utils/network/sonic/argspec/dcbx/dcbx.py
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/config/dcbx/__init__.py
  plugins/module_utils/network/sonic/config/dcbx/dcbx.py
  plugins/module_utils/network/sonic/facts/dcbx/__init__.py
  plugins/module_utils/network/sonic/facts/dcbx/dcbx.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/modules/sonic_dcbx.py
  plugins/modules/sonic_facts.py
  tests/regression/roles/sonic_dcbx/defaults/main.yml
  tests/regression/roles/sonic_dcbx/meta/main.yml
  tests/regression/roles/sonic_dcbx/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_dcbx/tasks/main.yml
  tests/regression/roles/sonic_dcbx/tasks/preparations_test.yaml
  tests/regression/roles/sonic_dcbx/tasks/tasks_template.yaml
  tests/regression/test.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_dcbx.yaml
  tests/unit/modules/network/sonic/test_sonic_dcbx.py
Labels: new_resource_module

#558 Add symlink for dcbx
  changelogs/fragments/558-dcbx-symlink.yaml
  meta/runtime.yml
  plugins/action/dcbx.py
Labels: bug

#538 BGP Graceful Restart Configuration Support
  changelogs/fragments/538-graceful-restart-support.yaml
  plugins/module_utils/network/sonic/argspec/bgp/bgp.py
  plugins/module_utils/network/sonic/config/bgp/bgp.py
  plugins/module_utils/network/sonic/facts/bgp/bgp.py
  plugins/modules/sonic_bgp.py
  tests/regression/roles/sonic_bgp/defaults/main.yml
  tests/unit/modules/network/sonic/fixtures/sonic_bgp.yaml
Labels: enhancement

#512 Add support to configure user ssh key
  changelogs/fragments/512-user-ssh-key.yaml
  plugins/module_utils/network/sonic/argspec/users/users.py
  plugins/module_utils/network/sonic/config/users/users.py
  plugins/module_utils/network/sonic/facts/users/users.py
  plugins/modules/sonic_users.py
  tests/regression/roles/sonic_users/defaults/main.yml
  tests/unit/modules/network/sonic/fixtures/sonic_users.yaml
  tests/unit/modules/network/sonic/test_sonic_users.py
Labels: enhancement

#525 Add Bridge Layer 2 Protocol Tunneling resource module
  meta/runtime.yml
  plugins/action/br_l2pt.py
  plugins/module_utils/network/sonic/argspec/br_l2pt/__init__.py
  plugins/module_utils/network/sonic/argspec/br_l2pt/br_l2pt.py
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/config/br_l2pt/__init__.py
  plugins/module_utils/network/sonic/config/br_l2pt/br_l2pt.py
  plugins/module_utils/network/sonic/facts/br_l2pt/__init__.py
  plugins/module_utils/network/sonic/facts/br_l2pt/br_l2pt.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/modules/sonic_br_l2pt.py
  plugins/modules/sonic_facts.py
  tests/regression/roles/sonic_br_l2pt/defaults/main.yml
  tests/regression/roles/sonic_br_l2pt/meta/main.yml
  tests/regression/roles/sonic_br_l2pt/tasks/cleanup_tests.yaml
  tests/regression/roles/sonic_br_l2pt/tasks/main.yml
  tests/regression/roles/sonic_br_l2pt/tasks/preparation_tests.yaml
  tests/regression/roles/sonic_br_l2pt/tasks/tasks_template.yaml
  tests/regression/test.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_br_l2pt.yaml
  tests/unit/modules/network/sonic/test_sonic_br_l2pt.py
Labels: new_resource_module

#561 Fix typos in configuration examples for BGP neighbors AF
  changelogs/fragments/561-bgp-nbr-af-documentation.yaml
  plugins/modules/sonic_bgp_neighbors_af.py
Labels: documentation

#556 implement evpn_esi_multihome resource module
  meta/runtime.yml
  plugins/action/evpn_esi_multihome.py
  plugins/module_utils/network/sonic/argspec/evpn_esi_multihome/evpn_esi_multihome.py
  plugins/module_utils/network/sonic/argspec/facts/facts.py
  plugins/module_utils/network/sonic/config/evpn_esi_multihome/evpn_esi_multihome.py
  plugins/module_utils/network/sonic/facts/evpn_esi_multihome/evpn_esi_multihome.py
  plugins/module_utils/network/sonic/facts/facts.py
  plugins/modules/sonic_evpn_esi_multihome.py
  plugins/modules/sonic_facts.py
  tests/regression/roles/sonic_evpn_esi_multihome/defaults/main.yml
  tests/regression/roles/sonic_evpn_esi_multihome/meta/main.yml
  tests/regression/roles/sonic_evpn_esi_multihome/tasks/main.yml
  tests/regression/roles/sonic_evpn_esi_multihome/tasks/preperation_tests.yml
  tests/regression/roles/sonic_evpn_esi_multihome/tasks/tasks_template.yml
  tests/regression/test.yaml
  tests/unit/modules/network/sonic/fixtures/sonic_evpn_esi_multihome.yaml
  tests/unit/modules/network/sonic/test_sonic_evpn_esi_multihome.py
Labels: new_resource_module
